emberjs/emberjs-build

.travis.yml

http://docs.travis-ci.com/user/workers/container-based-infrastructure/
Running CI in docker container should be more performant. This is already
being done in
[ember/ember.js](https://github.com/emberjs/ember.js/blob/dca9c74de7136deff79b9cb2f2de4f6b6b8237c7/.travis.yml#L6-L10)

Cache `npm install` in CI

---

lib/ember-build.js
lib/get-build-runtime-tree.js

Fixes errors after https://github.com/emberjs/emberjs-build/commit/16f0b20867ff6d010457501f9da37205c4fc92c7.
See https://travis-ci.org/emberjs/ember.js/jobs/46403805 for an example.

Ensure runtime tree receives the packages.

---

lib/build-cjs-tree.js
lib/ember-build.js

Changes driven by attempting to integrate with [emberjs/data][1]
* configure an output build name and namespace
* skip building template compiler
* skip building the runtime
[1]: https://github.com/emberjs/data

Allow Configuration

---

lib/concatenate-es6-modules.js
package.json

The `ember` package has only a single file `lib/main.js` which is moved to `ember.js`, but we are globbing and selecting `ember/**/*.js` which does not match any files (since there are no sub-folders).
This fixes the Ember build, and allows us to update it again.

Allow no files to be matched during concat step.

---

lib/config/build-config.js
lib/ember-build.js
lib/utils/debug-tree.js
package.json
tests/config/build-config-test.js

Build Ember with `ENABLE_TREE_DEBUGGING=true ember s` will create duplicate copies of these trees for easier step review.

Add easy tree debugging.

---

package.json

Has a more permissive dep dependency on JSCS so that future updates do
not require bumping this again.

Bump broccoli-jscs version.

---

lib/ember-build.js
lib/get-build-template-compiler-tree.js
lib/get-es6-package.js
lib/htmlbars-package.js
tests/ember-build-test.js
tests/expected/htmlbars/htmlbars-test-helpers.js
tests/fixtures/htmlbars/dist/es6/htmlbars-test-helpers.js
tests/get-es6-package-test.js
tests/htmlbars-package-test.js

* Remove dead code.
* Split dev vendor trees and prod vendor trees.
* Ensure that `htmlbarsPackage` only returns the specific package (not
all packages).
* Add `test` only vendor components.
* Incorporate `test` only requirements into `this._name + '-tests.js'`
file.

Do not compile developmentOnly package vendorRequirements in prod.

---

lib/utils/replace-version.js
package.json

That module was created to extract the way ember.js and ember-data builds were tagged. That means that it took the version number in the packate.json and added the SHA (8 digits) if the version contained the
`+` sign, like in `1.11.0-beta.1+canary`, turning it into `1.11.0-beta.1+canary.1a2b3d4d`
Git repo version now first of all looks if the current commit is tagged. In that case, it just returns the tag. P.e `v1.10.0-beta.4`.
If the commit is not tagged, it returns the the version in the package.json followed by the SHA, always.
I think this workflow can also work for ember.js and ember-data without any problem, escept that seems that ember.js tags contains a `v` at the beginning, while the version number in package.json doesn't, so it has to be deleted.

Upgraded git-repo-version to 0.1.0 (Support for tags)

---

lib/concatenate-es6-modules.js
lib/ember-build.js
lib/es6-vendored-package.js
lib/get-build-runtime-tree.js
lib/get-build-template-compiler-tree.js
lib/get-es6-package.js
lib/get-package-dependency-tree.js

Allow `vendorPackages` as a configuration option. If the argument is
missing, fall back to `getVendoredPackages()`

Accept Vendor Packages

---

lib/concatenate-es6-modules.js
lib/utils/transpile-es6.js
package.json
tests/expected/packages/ember-tests.js

There are still a number of issues with vendor packages, which is why they are not updated already.
Vendor package issue: using `strict` mode with Esperanto causes `this` in the root of a module to be rewritten to `undefined`. This causes things like backburner to break.  I still need to figure out exactly how to work around that...

Change to Esperanto for compiling Ember's packages.

---

lib/jscs-tree.js
package.json

Fix upstream: https://github.com/kellyselden/broccoli-jscs/pull/16
This is mostly a short-term work around.

Ensure JSCS output is escaped properly.

---

lib/ember-build.js
lib/get-es6-package.js
lib/utils/inline-template-precompiler.js
package.json
tests/get-es6-package-test.js

It should be supplied from the consuming project (makes tracking the
deps much easier).

Do not require HTMLBars from emberjs-build.

---

lib/utils/transpile-es6.js
package.json
tests/concatatinate-es6-modules-test.js
tests/expected/packages/ember-tests.js
tests/fixtures/transpile-es6/arrow-functions/some-file.js
tests/utils/transpile-es6-test.js

Replaces #68.
This does increase initial boot time (almost double), but does not seem to impact rebuild times.

Allow the use of ES2015 features in Ember build.

---

package.json

I believe this version includes the fix to unblock https://github.com/emberjs/ember.js/pull/10637 per the discussion at https://github.com/jscs-dev/node-jscs/issues/1171.

Bumping broccoli-jscs version

---

lib/config/test-config-tree.js

Without this change the js files in this directory do not get served by the `ember serve` command https://github.com/emberjs/data/tree/master/tests. Let me know if there is a better place for Ember Data to keep these files.

Ember Data uses js files in its tests dir

---

lib/concatenate-es6-modules.js
lib/get-build-template-compiler-tree.js
tests/ember-build-test.js

This is to allow future deprecations to work from within the AST plugins.

Add ember-debug to ember-template-compiler.

---

package.json

Misread what version JSCS only looked at ObjectExpressions for whitespace checking. This included JSCS 0.11.0.

Bumping JSCS to 0.0.20

---

lib/get-build-template-compiler-tree.js
package.json

Limiting the packages is a major future refactoring hazard, and is unlikely to be caught in the Ember test suite itself because the template compiler is loaded differently.

Do not limit ember-metal modules for template-compiler.

---

lib/utils/transpile-es6.js
package.json
tests/concatatinate-es6-modules-test.js

Enables `loose` mode, to prevent extra helpers (and avoid using `Array.isArray`).
More fixes still coming by @danmcclain, but this gets us a step closer.

Update to Babel 5.0.0.

---

lib/utils/transpile-es6.js

Samples:
```javascript
// input:
for (var i = 0; i < 3; i++) {
let j = i * i;
console.log(j);
}
console.log(j); // will throw
// output:
for (var i = 0; i < 3; i++) {
var _j = i * i;
console.log(_j);
}
console.log(j); // will throw
```
```javascript
// input:
function f() {
let j = data.length;
console.log(j, 'items');
for (let i = 0; i < j; ++i) {
let j = data[i] * data[i];
console.log(j); // squares
}
}
// output:
function f() {
var j = data.length;
console.log(j, 'items');
for (var i = 0; i < j; ++i) {
var _j = data[i] * data[i];
console.log(_j); // squares
}
}
```

Enable es6.blockScoping for Babel.

---

lib/utils/transpile-es6.js

Sample
```js
// input:
var prop = "foo";
var o = {
otherProp: 1,
[prop]: "bar",
['groot'.replace(/o/g,'e')]() {
console.log("hey there");
}
};
// output:
var _o;
var prop = "foo";
var o = (_o = {}, _o.otherProp = 1, _o[prop] = "bar", _o["groot".replace(/o/g, "e")] = function () {
console.log("hey there");
}, _o);
```

Enable es6.properties.computed for Babel

---

lib/utils/transpile-es6.js
package.json

enable it with DISK_CACHE=true
explicitly purge it with PURGE_DISK_CACHE=true
Once a better cache key can be derived, we can try to enable it by default

add support for experimental caching of the ES6 step

---

lib/utils/transpile-es6.js

During ember's own build babel is spewing deprecations. This config change should fix it, but I got blocked in trying to test this due to https://github.com/emberjs/emberjs-build/issues/108

Stop babel deprecation spew for es6.parameters.rest

---

.travis.yml
lib/utils/transpile-es6.js
package.json

This was being done by Esperanto before it was removed, unfortunately we
did not add `"useStrict"` to the whitelist when we removed Esperanto so
we have been running without strict mode since some timeframe in
1.13.0-beta cycle.

Add useStrict to `babel` config.

---

package.json

before:
```
➜  ember.js git:(master) ✗ ember s
version: 0.2.7
A new version of ember-cli is available (1.13.8). To install it, type ember update.
Livereload server on port 35729
Serving on http://localhost:4200/
[BABEL] Note: The code generator has deoptimised the styling of "ember/tests/routing/basic_test.js" as it exceeds the max of "100KB".
Build successful - 51362ms.
Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 17555ms
Babel                                         | 6110ms
Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (19)                                    | 29349ms (1544 …
```

use persistent filter for babel

---

lib/utils/transpile-es6.js

Inlines @chadhietala's amd-name-resolver with a small tweak, to prevent an error from being thrown in the case where `../` is used from a top level module.  That is intentionally done in HTMLBars to allow cross package requires in CJS modules. It may be possible to fix/change that upstream, but that work should not block this...

Automatically resolve relative paths.

---

lib/concatenate-es6-modules.js
lib/utils/conditional-use-strict-babel-plugin.js
lib/utils/transpile-es6.js
package.json
tests/fixtures/transpile-es6/conditional-use-strict/with-no-use-strict-directive.js
tests/fixtures/transpile-es6/conditional-use-strict/with-use-strict-directive.js
tests/fixtures/transpile-es6/conditional-use-strict/without-directive.js
tests/utils/transpile-es6-test.js

Copy the Babel internal `useStrict` plugin and modify slightly for our needs.

Remove broccoli-use-strict-remover in favor of Babel plugin.

---

lib/concatenate-es6-modules.js
lib/config/build-config.js
lib/utils/babel-enifed-module-formatter.js
lib/utils/transpile-es6.js
package.json
tests/concatatinate-es6-modules-test.js
tests/config/build-config-test.js

This is a bit of a hack, but proper support has been PR'ed upstream and is awaiting feedback. Hopefully, when that lands we can simply specify the `defineId` option and remove this horrible plugin.
In the meantime, I think we should move ahead. This shaves another 3-5 seconds off of warm boot on a production build (from 19s down to 15s).

Remove derequire step via customization of AMD formatter.

---

lib/ember-build.js
lib/minify-source-tree.js

* enabled: isn’t a valid option
* sourceMapConfig.enabled is
see: https://github.com/ef4/broccoli-uglify-sourcemap/blob/master/index.js#L27-L30

fix sourceMaps & minification config

---

lib/es6-vendored-package.js
lib/vendored-package.js
tests/vendored-package-test.js

We no longer need to muck with the custom destination paths here.

Remove unneeded tree manipulation.

---

lib/ember-build.js
lib/minify-source-tree.js

V8 heuristics around IIFE's is pretty narrow and only eagerly compiles
and parses IIFEs if they begin with a paren. When iife negation is
turned on in uglify, it removes the parens and replaces them with the !
IIFE syntax which causes V8 to lazily parse functions that are meant to
be eager. Adding this flag opts out of the ! IIFE transform. @krisselden
is also opening an issue on the uglify project to change the default.
Currently you will notice that on V8, prod builds will parse/eval faster
than min builds... which is bonkers.
Reference:
https://github.com/v8/v8/blob/master/src/parsing/parser.cc#L4272-L4307

Remove IIFE negation

---

lib/utils/transpile-es6.js
tests/fixtures/transpile-es6/classes/some-file.js
tests/utils/transpile-es6-test.js

By default, Babel sets `__proto__` to make static inheritance work.
However, this does not work in IE <= 10, so we need to transpile that
into ~= `Object.assign(...)`. This requires you to not change the static
functions/members once inherited, but that should be fine for us.

Transpile __proto__ to assign

---

lib/ember-build.js

The ember-tests.js file already includes the testVendorTrees, but when that was added I forgot to also update ember-tests.prod.js too.
:(

Fix prod builds using testVendorTrees.

---

lib/get-es6-package.js
lib/utils/glimmer-template-precompiler.js

Allows HTMLBars precompiler for `ember-htmlbars` templates, and `glimmer-engine` precompiler for `ember-glimmer` templates.

Make precompiler dependent on package being precompiled.

---

lib/ember-build.js
lib/get-build-runtime-tree.js
lib/get-build-template-compiler-tree.js

Actually pass through options.vendorPackages in all cases, so that getVendoredPackages() isn't used when this is passed in.

Actually pass through options.vendorPackages

---

lib/get-build-template-compiler-tree.js
lib/utils/glimmer-template-precompiler.js
lib/utils/htmlbars-template-precompiler.js
tests/ember-build-test.js

This just bundles both template compilers if they are both present.

Build infra changes for splitting the template compilers

---

lib/ember-build.js
lib/get-build-template-compiler-tree.js
lib/utils/glimmer-template-precompiler.js
lib/utils/htmlbars-template-precompiler.js
tests/ember-build-test.js
tests/expected/concat-tests/ember-tests.js
tests/get-es6-package-test.js
tests/htmlbars-package-test.js

As of https://github.com/emberjs/ember.js/pull/13843 these packages are now used only for generating `ember-template-compiler.js` asset, and are not required for runtime concerns.

Remove ember-template-compiler packages from ember.*.js.

---

lib/utils/babel-enifed-module-formatter.js
lib/utils/conditional-use-strict-babel-plugin.js
lib/utils/transpile-es6.js

This removes the custom monkey patches that we did to add proper
invalidations to the feature flagging plugin.  This has now been fixed
upstream by default.
See https://github.com/babel/broccoli-babel-transpiler/pull/89 for details.

Babel plugin cache invalidation has been fixed, use it.

---

lib/ember-build.js
lib/get-es6-package.js
lib/utils/glimmer-template-precompiler.js
package.json

Require that the consuming app provide the `glimmer` to be used.

Remove usage of glimmer-template-precompiler.

---

lib/concatenate-es6-modules.js
lib/ember-build.js
lib/get-vendored-packages.js
lib/utils/babel-strip-class-call-check.js
lib/utils/transpile-es6.js
package.json
tests/concatinate-es6-modules-test.js
tests/expected/concat-tests/ember-tests.js
tests/expected/transpile-es6/classes/some-file.js

This adds the ability to externalize babel's helpers and provide our own custom implementation of those helpers. It also experiments with the idea of a non-feature dependent flagging system that allows us to dead code eliminate arbitrary blocks in Ember. While I've limited the usage Uglify's `global_defs` to `DEV_MODE` to compile away checks in the babel helpers, this may be an avenue to for deprecated feature stripping.
Depends on https://github.com/babel/broccoli-babel-transpiler/pull/96

Externalize babelHelpers and strip classCallChecks

---

lib/concatenate-es6-modules.js
lib/utils/babel-enifed-module-formatter.js
lib/utils/babel-strip-class-call-check.js

`options.includeDevHelpers` is specified when we are doing a `ember.debug.js` build.
Before this change, when `options.includeDevHelpers` was true we would strip the `class-call-check` helper from invocations but include the helper itself in the build ( as part of the `external-helpers-dev.js`), and when `optioins.includeDevHelpers` was `false` we would leave the `class-call-check` invocations in the build but **not** include the helper itself in the build (as part of the `external-helpers-prod.js` file).
As you can see the relationship between `includeDevHelpers` and `stripRuntimeChecks` must be an inverse relationship, or the production build will error.

Invert `stripRuntimeChecks` option.

---

lib/get-build-template-compiler-tree.js
lib/utils/glimmer-template-precompiler.js

* Does not try to embed it in the ember-template-compiler.
* Updates import to use relative import for `template` function (all
templates are in the same package so we should be using relative import).

Allow ember-templates package to be removed.

---

lib/get-build-template-compiler-tree.js
tests/ember-build-test.js

This replaces the dependency on container (needed for `getOwner` / `setOwner` things).
In the long run, we need to move `assert` / `deprecate` / etc out of `ember-metal` so that we can remove ember-template-compiler's dep on `ember-metal` completely.

Update ember-template-compiler.js output to include ember-utils.
