emberjs/emberjs-build

package.json
Changes are here: https://github.com/tildeio/htmlbars/compare/v0.7.2...v0.8.0
=> Bump HTMLBars version to 0.8.0.

lib/ember-build.js, package.json
=> Switch to CoreObject

package.json
=> Bump broccoli-derequire version.

package.json
=> Bumping Broccoli-JSCS 0.0.22

lib/utils/transpile-es6.js
https://github.com/tildeio/htmlbars/pull/330
=> Add CJS / UMD support to `transpileES6`

package.json
See: https://github.com/cibernox/git-repo-version/pull/7 https://github.com/emberjs/ember.js/issues/11256
=> Update git-repo-version to align with SemVer

lib/utils/transpile-es6.js
=> * existing of ENV key should be sufficient to enable

lib/config/build-config.js, lib/utils/transpile-es6.js
Addresses https://github.com/emberjs/emberjs-build/issues/105 temporarily.
=> Disable sourcemaps when minifying.

package.json
=> Bump broccoli-sourcemap-concat

features.json, lib/concatenate-es6-modules.js, lib/config/build-config.js, lib/config/defeatureify-config.js, lib/ember-build.js, package.json, tests/config/build-config-test.js, tests/config/defeatureify-config-test.js
This is now handled by a babel plugin instead.
=> Remove defeatureify

lib/concatenate-es6-modules.js, lib/utils/transpile-es6.js, package.json
The things we use in here, _assign and _merge, did not have changes affecting this project.
=> Upgrade to a supported version of lodash.

lib/minify-source-tree.js
I tested with npm link in ember
=> fix minifySourceTree

lib/get-build-runtime-tree.js, lib/get-build-template-compiler-tree.js
Addresses https://github.com/emberjs/ember.js/issues/13234.
=> Use the correct sourcemap config.

lib/get-build-template-compiler-tree.js, tests/ember-build-test.js
@krisselden did I miss something?
=> Ember console

lib/utils/transpile-es6.js, package.json
Made some changes in amd-name-resolver to allow for `continue` and `throw`. Removing the copypasta.
=> Use amd-name-resolver

.travis.yml
=> TravisCI: Replace io.js with Node.js matrix

tests/helpers/ensure-method-returns-tree.js
=> Increase test timeouts in ensureMethodReturnsTree() test generator

lib/utils/babel-enifed-module-formatter.js, lib/utils/conditional-use-strict-babel-plugin.js
Upstream issue/failing test: https://github.com/stefanpenner/hash-for-dep/pull/30
=> Work around an issue in hash-for-dep with nested requires.

lib/utils/glimmer-template-precompiler.js
=> Update glimmer precompiler for upstream changes.

lib/concatenate-es6-modules.js, lib/ember-build.js
Porting https://github.com/emberjs/ember.js/pull/15112.
cc @rwjblue
=> Ensure Ember.Test globals setup for ember-testing.js

lib/ember-build.js
=> Fix quotes linting error
